print("Mi nombre es", "Python.", end=" ")
print("Monty Python.")
print()
print("---------------------------------")
print("Mi nombre es", "Python.", end="")
print("Monty Python.")
print()
print("---------------------------------")
print('Fresa', 'Naranja', 'Mandarina', end=" ")
print('Uva', 'Sandia')
print()
print("---------------------------------")
print('Deseamos unir dos líneas en una ', end=', ')
print('y veremos que se vuelven una sola.')
print()
print("---------------------------------")
print('el resultado es:', end=" ---> ")
print("50")
print()
print("---------------------------------")
print("Saludar", end=" ")
print('a todos', end='!')
print()
print()
print("---------------------------------")
print("Podemos usar end para", end="\n")
print("cambios de línea")
print()
print("---------------------------------")
print('podemos delimitar el espaciado así', end="         ")
print('linea anexa')
print()
print("le veremos gran utilidad cuando veamos ciclos repetitivos")
