print("La witsi Araña subio a su telaraña.")
print('Vino la lluvia y se la llevó.')
print('-----------------------------------')
print("La witsi Araña subio a su telaraña.")
print()
print('Vino la lluvia y se la llevó.')
print()
print('-----------------------------------')
print("La witsi Araña subio \na su telaraña.")
print()
print('Vino la llu\nvia y se la llevó.')
print()
print('-----------------------------------')
print("Estas en el directorio C:\Windows")
print("\\")
print()
print('-----------------------------------')
print("Argumento 1", "Argumento 2", 'Argumento 3')
print()
print("Mi nombre es", "Juan")
print("Saludos a todos")
