print('Ahora', 'utilizando', 'ambos', 'juntos', end='!!!', sep='_')
print()
print('---------------------')
print('1', '2', '3', '4', '5', end='...', sep='-')
print()
print('---------------------')
print('Python', 'es', 'divertido', sep='\n', end='!')
print()
print('---------------------')
print("I'm study Python")
print('hola me llamo "Juan" estudio Python')
