print('Estoy', 'trabajando', 'el', 'uso', 'de', 'separador', sep='-')
print()
print('-------------------------------------')
print('Otro ejemplo de uso', 'de sep en mi script', sep=' ')
print()
print('-------------------------------------')
print('1','2','3', sep=',')
print()
print('-------------------------------------')
print(*"Bienvenidos", sep='\n')
print()
print('Veremos el uso de sep en ciclos repetitivos y despliegues de resultados')
