print(2 + 2)

print(10 + 10 / 2)

print(2 - 3 * 6)
print('---------------')

print(2 ** 3)
print(2 ** 3.)
print(2. ** 3)
print(2. ** 3.)
print()

print('---------------')
print(6 * 3)
print(6 / 3)
print()
print('---------------')

print('Operadores aritmeticos division entera')
print(6 // 3)
print(6 // 3.)
print(6. // 3)
print(6. // 3.)
print()
print('---------------')
print(6 // 4)
print(6. // 4)
print()
print('---------------')
print(14 % 4)
print(14/4)
print(14//4)
print()
print('---------------')
print('Operador suma')
print(-4 + 4)
print(-4. + 8)
print(+2)
print(2)
print()
print('---------------')
print('Operador resta')
print(-4 - 4)
print(4. - 8)
print(-1.1)
print()
print('---------------')
print("Orden de potencias")
print(2 ** 2 ** 3)
print()
print('---------------')

print('orden de prioridad por parentesis')

print((5 * ((25 % 13) + 100) / (2 *13)) // 2)
